apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

labels:
  - pairs:
      environment: production
    includeSelectors: true

resources:
  - ../../base
  - hpa.yaml
  - ingress.yaml

patches:
  - path: deployment-patch.yaml
