apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

labels:
  - pairs:
      environment: dev
    includeSelectors: true

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
